services:
  backend:
    build:
      context: ./CanalDenuncia_Back
      dockerfile: Dockerfile
    container_name: canal-denuncias-backend-prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - canalDenuncia-network-prod
    volumes:
      - ./uploads:/uploads

  frontend:
    build:
      context: ./CanalDenuncia_Front
      dockerfile: Dockerfile
    container_name: canal-denuncias-frontend-prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - canalDenuncia-network-prod

volumes:
  canal-denuncias-db-data-prod:

networks:
  canalDenuncia-network-prod:
    driver: bridge
