spring.application.name=CanalDenuncia_Back
FRONT_URL=${FRONT_URL}
spring.profiles.active=${PROFILE:prod}

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jackson.time-zone=America/Sao_Paulo

# DevTools - hot reload dentro do Docker
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# Dados do servidor SMTP (ex: Gmail, Mailtrap, SendGrid, etc.)
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASSWORD}

# Propriedades extras de segurança
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email 
email.destinatario=${EMAIL_DESTINATARIO}

# AES-256 Chave de criptografia do CPF
canal.crypto.secret=${CPF_ENCRYPTION_KEY}
canal.crypto.salt=${CPF_ENCRYPTION_SALT}

